# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.2
_src_path: https://github.com/trobz/trobz-python-template.git
author_email: doanhduyxavie@gmail.com
author_username: Do Anh Duy
enable_docs_site: true
enable_github_action: true
package_name: odoo_db
project_description: Odoo databases management CLI tool
project_name: odoo-db
project_type: cli
publish_to_pypi: true
repository_name: odoo-db
repository_namespace: trobz
